### ISSUE TITLE
Running on Windows / building docs

### ISSUE THREAD

**Issue by Czechball** [tfrere/music-to-led#5]
I'd like to run this on Windows, but when I tried just running "npm build" and "npm start", it failed. Here's the log:
[2021-05-17T11_53_54_157Z-debug.log](https://github.com/tfrere/music-to-led/files/6493565/2021-05-17T11_53_54_157Z-debug.log)

This is the error when trying to run "npm start":

```
App threw an error during load
TypeError: i.systemPreferences.askForMediaAccess is not a function
    at Module../app/main.dev.ts (D:\Documents\music-to-led\app\main.prod.js:2:7462)
    at n (D:\Documents\music-to-led\app\main.prod.js:2:124)
    at module.exports../app/constants/python.json (D:\Documents\music-to-led\app\main.prod.js:2:923)
    at Object.<anonymous> (D:\Documents\music-to-led\app\main.prod.js:2:950)
    at Module._compile (internal/modules/cjs/loader.js:880:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:892:10)
    at Module.load (internal/modules/cjs/loader.js:735:32)
    at Module._load (internal/modules/cjs/loader.js:648:12)
    at Module._load (electron/js2c/asar.js:717:26)
    at Function.Module._load (electron/js2c/asar.js:717:26)
```
and then the process froze.

My environment: Python 3.8.5 running from Minoconda3, npm 6.14.8 - Windows 10 20H2 build 19042.985

It'd be really nice to have some kind of building instructions or maybe even binaries for Windows.

**Comment by tfrere** [comment]
Hi Czechball, 

Thanks for your interest ! 

Unfortunately, as it's described in the readme.md,
Music-to-led is currently developed for MacOs and Linux platforms only,
that's why i'm not providing any binaries for Windows.

That being said,
if you want to help for Windows portability,
you can start by the [server part ](https://github.com/tfrere/music-to-led-server)

There are two issues to make it work for windows :
- Multiprocessing
- Serial communication handling

Feel free to ask if you have some questions !
